Repository unixporn/robbb, pull requests merged in 2021-07, with the labels that each got.

#169 remove mod blocklist immunity (fixes #160)
  src/events/message_create.rs
Labels: Moderation, important

#176 added kick command for #166
  src/commands/kick.rs
  src/commands/mod.rs
Labels: Moderation, enhancement

#185 add script to generate environment variables
  README.md
  gen-env.sh
Labels: enhancement, not a bug
